server:
  port: 8081

spring:
  application:
    name: customer-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecret

stripe:
  secret-key: sk_test_customer

sendgrid:
  api-key: SG_customer

twilio:
  account-sid: AC_customer
  auth-token: AUTH_customer
