spring:
  application:
    name: security-service

  datasource:
    url: jdbc:mysql://localhost:3306/securitydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost       # replace with redis-server / cloud host in prod
      port: 6379
      timeout: 600000
      # password: yourRedisPassword   # (uncomment if Redis is password protected)

server:
  port: 8085

jwt:
  secret: mySecretKey123
  expiration: 3600000  # 1 hour in ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
