spring:
  application:
    name: security-service

server:
  port: 8085

jwt:
  secret: mySecretKey123
  expiration: 3600000  # 1 hour in ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Redis config
spring:
  data:
    redis:
      host: localhost       # change to redis-server or AWS endpoint in prod
      port: 6379
      timeout: 60000        # 60s timeout
